FROM jkig/apb-base

LABEL "com.redhat.apb.spec"=\
"dmVyc2lvbjogMS4wCm5hbWU6IGxhc3Qtb3BlcmF0aW9uLWRlbW8tYXBiCmRlc2NyaXB0aW9uOiBk\
ZXBsb3lzIGFuIGFwcGxpY2F0aW9uIGRlbW9uc3RyYXRpbmcgdGhlIHVzZSBvZiB0aGUgTGFzdCBP\
cGVyYXRpb24gTW9kdWxlCmJpbmRhYmxlOiBGYWxzZQphc3luYzogb3B0aW9uYWwKbWV0YWRhdGE6\
CiAgZGlzcGxheU5hbWU6IExhc3QgT3BlcmF0aW9uIERlbW8gKEFQQikKICBsb25nRGVzY3JpcHRp\
b246IEEgc2FtcGxlIEFQQiB3aGljaCBkZXBsb3lzIGEgY29udGFpbmVyaXplZCBIZWxsbyBXb3Js\
ZCB3ZWIgYXBwbGljYXRpb24gZGVtb25zdHJhdGluZyBMYXN0IE9wZXJhdGlvbgogIGRlcGVuZGVu\
Y2llczogWydkb2NrZXIuaW8vYW5zaWJsZXBsYXlib29rYnVuZGxlL2hlbGxvLXdvcmxkOmxhdGVz\
dCddCiAgcHJvdmlkZXJEaXNwbGF5TmFtZTogIlJlZCBIYXQsIEluYy4iCnBsYW5zOgogIC0gbmFt\
ZTogZGVmYXVsdAogICAgZGVzY3JpcHRpb246IEEgc2FtcGxlIEFQQiBkZW1vbnN0cmF0aW5nIHRo\
ZSBMYXN0IE9wZXJhdGlvbiBtb2R1bGUKICAgIGZyZWU6IFRydWUKICAgIG1ldGFkYXRhOgogICAg\
ICBkaXNwbGF5TmFtZTogRGVmYXVsdAogICAgICBsb25nRGVzY3JpcHRpb246IFRoaXMgcGxhbiBk\
ZXBsb3lzIGEgUHl0aG9uIHdlYiBhcHBsaWNhdGlvbiBkaXNwbGF5aW5nIEhlbGxvIFdvcmxkIGRl\
bW9uc3RyYXRpbmcgTGFzdCBPcGVyYXRpb24KICAgICAgY29zdDogJDAuMDAKICAgIHBhcmFtZXRl\
cnM6IFtdCg=="

ADD playbooks /opt/apb/actions
ADD roles /opt/ansible/roles
RUN chmod -R g=u /opt/{ansible,apb}

USER apb
